### ISSUE TITLE
Bash and Powershell?

### ISSUE THREAD

**Issue by awilliansd** [piotr-rojek/devopsifyme-sbemulator#23]
I saw your explanation, but I can't inject certificate in container, how could I inject this certificate?

![image](https://github.com/piotr-rojek/devopsifyme-sbemulator/assets/4139802/9d76d060-921a-43b8-862f-75d3f7c0ca7c)

**Comment by awilliansd** [comment]
Someone?

**Comment by vechkar** [comment]
check if you are using the right container prefix. Try printing $containerPrefix and also "docker ps " just to ensure you are using the correct container prefix.
